name: first
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  windows:
    needs: ubuntu
    runs-on: windows-latest
    steps:
      run: date
  macos:
    needs: windows
    runs-on: macos-latest
    steps:
      - run: date
  depends:
    needs: macos
    runs-on: ubuntu-latest
    steps:
      - run: date
